pr_c = 'cyan'
ch_c = 'yellow'
red_c = 'red'
black_c = 'lime'
nrh_c = 'DeepSkyBlue'
purple_c = 'DarkViolet'
num_c = "orange"
norm_c = 'white'
font_c_cut = 'black'
font_c = '"' + font_c_cut + '"'
special_c = "DeepPink"
